### ISSUE TITLE
Additonal values required

### ISSUE THREAD

**Issue by DieSeef** [Kleinrotti/hass-senertec#8]
Hi Kleinrotti,

sorry to bother you again.
Any chance to also add "Produzierter Strom Heute", "Produzierte Wärme Heute" and "Betriebsstunden Heute"?

![image](https://github.com/Kleinrotti/hass-senertec/assets/131398023/d562df4f-f01d-4a56-a9c4-35aaabe301c5)

Sorry i would love to support you by doing it myself but unfortunatley i´m not a developer, just a IT infrastructure guy ;-)

**Comment by Kleinrotti** [comment]
Unfortunately not. These value are calculated by the Dachsportal itself and doesn't come from the heating system.
But you can use Homeassistant sensors to calculate it.

Here is some example code from my Homeassistant instance. You have to replace the source value with your sensor name.

sensors.yaml
```yaml
- platform: integration
  source: sensor.xxxxx_power_inverter
  name: heizung_power_produced
  unit_prefix: k
  round: 2
  method: left
```
configuration.yaml
```yaml
utility_meter:
  heizung_power_produced_daily:
    source: sensor.heizung_power_produced
    cycle: daily
```

Maybe this helps
